"use client";

import { useEffect, useMemo, useState } from "react";

type Area = { id: string; label: string; short: string; color: string; icon: string; desc: string; stat: string };
type Question = { id: string; area: string; type: string; level: string; title: string; body: string; choices?: string[]; answer: string; explanation: string; process: string[]; concept: string };

const areas: Area[] = [
  { id: "korean", label: "의사소통 국어", short: "국어", color: "coral", icon: "ㄱ", desc: "문서 이해와 표현", stat: "72%" },
  { id: "english", label: "의사소통 영어", short: "영어", color: "blue", icon: "A", desc: "업무 영어와 독해", stat: "64%" },
  { id: "math", label: "수리활용 영역", short: "수리", color: "mint", icon: "∑", desc: "자료 해석과 계산", stat: "81%" },
  { id: "problem", label: "문제해결 영역", short: "문제해결", color: "purple", icon: "⌁", desc: "논리적 사고와 해결", stat: "58%" },
  { id: "adapt", label: "직무적응 영역", short: "직무적응", color: "yellow", icon: "✦", desc: "조직과 업무 적응", stat: "76%" },
];

const questions: Question[] = [
  { id: "q1", area: "korean", type: "문서이해", level: "중급", title: "핵심 내용을 찾아보세요", body: "다음 공지문의 내용으로 가장 적절한 것은 무엇입니까?\n\n‘하반기부터 모든 팀은 회의 전 안건을 공유하고, 회의 후 24시간 이내에 결정사항을 기록한다. 이를 통해 회의의 효율성과 실행력을 높이고자 한다.’", choices: ["회의 시간을 줄이는 것이 가장 큰 목적이다.", "회의 전후의 기록을 표준화하는 것이 핵심이다.", "하반기부터 회의 자체를 없애려 한다.", "안건 공유는 회의 후에 진행한다."], answer: "회의 전후의 기록을 표준화하는 것이 핵심이다.", explanation: "공지문은 회의 전 안건 공유와 회의 후 결정사항 기록을 함께 요구합니다. 따라서 전후 기록을 표준화한다는 선택지가 핵심을 정확히 요약합니다.", process: ["실행 지침을 시간 순서로 나눕니다.", "‘전’과 ‘후’에 해당하는 행동을 찾습니다.", "두 행동을 묶는 목적을 선택합니다."], concept: "핵심 내용 요약" },
  { id: "q2", area: "math", type: "자료해석", level: "중급", title: "변화율을 계산해보세요", body: "어떤 교육 프로그램의 참여자가 1분기 120명에서 2분기 150명으로 증가했습니다. 전 분기 대비 증가율은 얼마입니까?", choices: ["20%", "25%", "30%", "35%"], answer: "25%", explanation: "증가한 인원은 30명(150-120)입니다. 기준이 되는 1분기 인원 120명으로 나누면 30 ÷ 120 = 0.25, 즉 25%입니다.", process: ["증가량을 계산합니다: 150-120=30명", "기준값인 이전 분기로 나눕니다: 30÷120", "백분율로 바꿉니다: 0.25×100=25%"], concept: "증가율 계산" },
  { id: "q3", area: "english", type: "업무독해", level: "초급", title: "Choose the best response", body: "Please submit the revised report by Friday afternoon.\n\nWhat is the most appropriate response?", choices: ["I will send it by Friday afternoon.", "I sent it yesterday tomorrow.", "Friday is a report.", "Please submit me."], answer: "I will send it by Friday afternoon.", explanation: "요청에 대한 적절한 응답은 기한을 확인하고 행동을 약속하는 문장입니다. ‘I will send it by Friday afternoon.’이 자연스럽습니다.", process: ["요청의 핵심 동사 submit을 확인합니다.", "기한 Friday afternoon을 유지합니다.", "미래의 약속 표현 will을 사용합니다."], concept: "업무 요청에 응답하기" },
];

const fallbackQuestion = questions[0];

export default function Home() {
  const [view, setView] = useState("home");
  const [areaId, setAreaId] = useState("korean");
  const [question, setQuestion] = useState(fallbackQuestion);
  const [answer, setAnswer] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [saved, setSaved] = useState(false);
  const [attempts, setAttempts] = useState(12);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [model, setModel] = useState("Gemini 3.5 Flash-Lite");
  const [key, setKey] = useState("");
  const area = areas.find((item) => item.id === areaId) ?? areas[0];
  const correct = answer === question.answer;

  useEffect(() => { const raw = localStorage.getItem("job-cert-settings"); if (raw) { const s = JSON.parse(raw); setModel(s.model || model); setKey(s.key || ""); } }, []);
  useEffect(() => { localStorage.setItem("job-cert-attempts", String(attempts)); }, [attempts]);
  const progress = useMemo(() => submitted ? 50 : 25, [submitted]);

  function chooseArea(id: string) { setAreaId(id); const match = questions.find((q) => q.area === id) ?? fallbackQuestion; setQuestion(match); setAnswer(""); setSubmitted(false); setSaved(false); setView("practice"); }
  function submit() { if (!answer) return; setSubmitted(true); setAttempts((v) => v + 1); }
  function next() { const idx = questions.findIndex((q) => q.id === question.id); const nextQ = questions[(idx + 1) % questions.length]; setQuestion(nextQ); setAreaId(nextQ.area); setAnswer(""); setSubmitted(false); setSaved(false); }
  function saveSettings() { localStorage.setItem("job-cert-settings", JSON.stringify({ model, key })); setSettingsOpen(false); }

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">C</span><span>커리어<span className="brand-accent">스텝</span></span></div>
      <div className="side-label">학습 메뉴</div>
      <nav>{[["home", "⌂", "대시보드"], ["areas", "◈", "인증영역"], ["history", "▤", "학습 기록"], ["wrong", "♡", "오답노트"]].map(([id, icon, label]) => <button key={id} className={view === id ? "nav-item active" : "nav-item"} onClick={() => setView(id)}><span>{icon}</span>{label}</button>)}</nav>
      <div className="side-bottom"><div className="tip-card"><span className="tip-icon">✦</span><div><strong>오늘의 목표</strong><p>문제 3개 풀기</p><div className="mini-progress"><i style={{ width: "66%" }} /></div></div></div><button className="profile" onClick={() => setSettingsOpen(true)}><span className="avatar">서</span><span><b>서준님</b><small>개인 설정</small></span><span className="dots">⋮</span></button></div>
    </aside>
    <section className="content">
      <header className="topbar"><div className="breadcrumb">커리어스텝 <span>/</span> {view === "home" ? "대시보드" : view === "practice" ? "문제 풀이" : view === "wrong" ? "오답노트" : "학습 기록"}</div><div className="top-actions"><span className="demo-badge">● 데모 모드</span><button className="icon-btn" onClick={() => setSettingsOpen(true)}>⚙</button></div></header>
      {view === "home" && <HomeView onChoose={() => setView("areas")} onHistory={() => setView("history")} />}
      {view === "areas" && <AreaView onChoose={chooseArea} />}
      {view === "practice" && <PracticeView area={area} question={question} answer={answer} setAnswer={setAnswer} submitted={submitted} correct={correct} progress={progress} saved={saved} onSubmit={submit} onNext={next} onSave={() => setSaved(true)} onBack={() => setView("areas")} onStudy={() => setView("supplement")} />}
      {view === "supplement" && <SupplementView question={question} area={area} onNext={next} />}
      {view === "history" && <HistoryView onRetry={chooseArea} />}
      {view === "wrong" && <WrongView onRetry={chooseArea} />}
    </section>
    {settingsOpen && <div className="modal-backdrop" onClick={() => setSettingsOpen(false)}><div className="modal" onClick={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">PERSONAL SETTINGS</p><h2>개인 설정</h2></div><button className="close" onClick={() => setSettingsOpen(false)}>×</button></div><label>Gemini API 키<span className="muted">서버에서만 사용되도록 암호화해 관리합니다.</span><input type="password" placeholder="AIza..." value={key} onChange={(e) => setKey(e.target.value)} /></label><label>선호 모델<select value={model} onChange={(e) => setModel(e.target.value)}><option>Gemini 3.5 Flash-Lite</option><option>Gemini 3.5 Flash</option><option>Gemini 3.5 Pro</option></select></label><label>기본 학습 영역<select><option>의사소통 국어</option><option>수리활용 영역</option><option>문제해결 영역</option></select></label><button className="primary full" onClick={saveSettings}>설정 저장하기</button></div></div>}
  </main>;
}

function HomeView({ onChoose, onHistory }: { onChoose: () => void; onHistory: () => void }) { return <div className="page"><div className="hero"><div><p className="eyebrow">YOUR NEXT STEP</p><h1>오늘도 한 걸음,<br /><em>나의 가능성</em>을 넓혀요.</h1><p className="hero-copy">직업공통능력 인증시험, 커리어스텝과 함께<br />나에게 맞는 속도로 준비해 보세요.</p><button className="primary" onClick={onChoose}>학습 시작하기 <span>→</span></button></div><div className="hero-art"><div className="sun" /><div className="art-card"><span>✦</span><b>이번 주 학습</b><strong>6.5h</strong><small>지난주보다 +1.2h</small></div><div className="art-circle">C</div></div></div><div className="section-heading"><div><p className="eyebrow">EXPLORE</p><h2>인증영역을 선택하세요</h2></div><button className="text-btn" onClick={onChoose}>전체 보기 →</button></div><div className="area-grid">{areas.map((a) => <button className={`area-card ${a.color}`} key={a.id} onClick={onChoose}><span className="area-icon">{a.icon}</span><span><b>{a.label}</b><small>{a.desc}</small></span><span className="area-arrow">↗</span></button>)}</div><div className="section-heading record-head"><div><p className="eyebrow">YOUR PROGRESS</p><h2>최근 학습 현황</h2></div><button className="text-btn" onClick={onHistory}>학습 기록 보기 →</button></div><div className="progress-card"><div className="progress-main"><span className="round-icon coral">ㄱ</span><div><b>의사소통 국어</b><p>문서이해 · 중급</p></div><strong>72<span>%</span></strong></div><div className="bar"><i style={{ width: "72%" }} /></div><div className="progress-foot"><span>최근 학습: 오늘 오전 10:24</span><span>12문제 풀이</span></div></div></div> }

function AreaView({ onChoose }: { onChoose: (id: string) => void }) { return <div className="page"><div className="page-title"><p className="eyebrow">CERTIFICATION AREAS</p><h1>어떤 영역을 공부할까요?</h1><p>현재 나의 학습 목표에 맞는 영역을 선택해 보세요.</p></div><div className="area-grid big">{areas.map((a) => <button className={`area-card ${a.color}`} key={a.id} onClick={() => onChoose(a.id)}><span className="area-icon">{a.icon}</span><span><b>{a.label}</b><small>{a.desc}</small><small className="area-stat">현재 정답률 {a.stat}</small></span><span className="area-arrow">→</span></button>)}</div><div className="setup-panel"><div><p className="eyebrow">QUICK SETUP</p><h3>문제 설정은 풀이 화면에서 바로 바꿀 수 있어요.</h3></div><span>문제 유형 · 난이도 · 문제 형식</span></div></div> }

function PracticeView({ area, question, answer, setAnswer, submitted, correct, progress, saved, onSubmit, onNext, onSave, onBack, onStudy }: any) { return <div className="page practice-page"><div className="practice-top"><button className="back" onClick={onBack}>← 영역 선택</button><div className="practice-settings"><span className={`tag ${area.color}`}>{area.label}</span><select defaultValue="문서이해"><option>문서이해</option><option>자료해석</option><option>업무독해</option></select><select defaultValue="중급"><option>초급</option><option>중급</option><option>고급</option></select></div></div><div className="practice-layout"><div className="question-panel"><div className="question-meta"><span>QUESTION 01</span><span>문제 유형 · {question.type}</span><span>난이도 · {question.level}</span></div><div className="progress-line"><i style={{ width: `${progress * 2}%` }} /></div><h1>{question.title}</h1><div className="question-body">{question.body.split("\n").map((line: string, i: number) => <p key={i}>{line || <>&nbsp;</>}</p>)}</div>{question.choices ? <div className="choices">{question.choices.map((choice: string, i: number) => <button key={choice} className={answer === choice ? "choice selected" : "choice"} onClick={() => !submitted && setAnswer(choice)}><span>{String.fromCharCode(65 + i)}</span>{choice}{submitted && choice === question.answer && <b className="choice-check">✓</b>}</button>)}</div> : <input className="answer-input" placeholder="답안을 입력하세요" value={answer} onChange={(e) => setAnswer(e.target.value)} disabled={submitted} />}{!submitted ? <button className="primary submit" onClick={onSubmit} disabled={!answer}>답안 제출하기 <span>→</span></button> : <div className="feedback"><div className={correct ? "feedback-title good" : "feedback-title bad"}><span>{correct ? "✓" : "!"}</span><div><b>{correct ? "정답이에요!" : "아쉬워요, 다시 확인해볼까요?"}</b><small>{correct ? "핵심 내용을 정확하게 파악했어요." : `정답은 ‘${question.answer}’입니다.`}</small></div></div><div className="feedback-copy"><b>정답 해설</b><p>{question.explanation}</p><b>풀이 과정</b><ol>{question.process.map((s: string) => <li key={s}>{s}</li>)}</ol></div><div className="feedback-actions"><button className="secondary" onClick={onStudy}>맞춤 보충학습 보기</button><button className={saved ? "saved secondary" : "secondary"} onClick={onSave}>{saved ? "✓ 오답노트에 저장됨" : "♡ 오답 저장"}</button><button className="primary" onClick={onNext}>다음 문제 <span>→</span></button></div></div>}</div><aside className="side-insight"><div className="timer-card"><span>풀이 시간</span><strong>00:42</strong><small>평균보다 8초 빨라요</small></div><div className="session-card"><div className="session-head"><b>이번 세션</b><span>1 / 3</span></div><div className="session-bar"><i style={{ width: submitted ? "33%" : "18%" }} /></div><p>오늘의 목표까지<br /><strong>2문제</strong> 남았어요</p></div><div className="hint-card"><span>✦</span><b>문제 풀이 TIP</b><p>지문에서 반복되거나 강조된 표현은 핵심 내용을 담고 있을 가능성이 높아요.</p></div></aside></div></div> }

function SupplementView({ question, area, onNext }: any) { return <div className="page supplement"><button className="back" onClick={onNext}>← 문제로 돌아가기</button><div className="page-title"><p className="eyebrow">PERSONALIZED BOOST</p><h1>지금 필요한 보충학습</h1><p><span className={`tag ${area.color}`}>{area.label}</span> 풀이 결과를 바탕으로 추천했어요.</p></div><div className="boost-grid"><div className="concept-card"><span className="boost-icon">◒</span><p className="eyebrow">WEAK CONCEPT</p><h2>{question.concept}</h2><p>문제의 핵심 정보를 빠르게 구조화하는 연습이 더 필요해요.</p><div className="concept-score"><span>취약도</span><b>주의</b><div className="bar"><i style={{ width: "68%" }} /></div></div></div><div className="lesson-card"><p className="eyebrow">MINI LESSON</p><h2>핵심 내용은 ‘행동 + 목적’으로 정리해요</h2><p>긴 지문을 읽을 때는 누가, 무엇을, 언제 하는지 먼저 표시한 뒤, 반복되는 행동을 하나의 문장으로 묶어보세요. 마지막으로 그 행동의 목적을 연결하면 핵심 내용이 선명해집니다.</p><div className="lesson-example"><span>예시</span> 회의 전 안건 공유 + 회의 후 기록 <b>→ 회의 기록 표준화</b></div></div><div className="similar-card"><div><p className="eyebrow">SIMILAR QUESTION</p><h2>유사 문제로 확인해 볼까요?</h2><p>새로운 문제 1개가 준비되어 있어요.</p></div><button className="primary" onClick={onNext}>풀어보기 →</button></div></div></div> }

function HistoryView({ onRetry }: { onRetry: (id: string) => void }) { return <div className="page"><div className="page-title"><p className="eyebrow">LEARNING HISTORY</p><h1>학습 기록</h1><p>꾸준히 쌓아온 나의 학습 데이터를 확인해 보세요.</p></div><div className="stats-row"><div><span>전체 정답률</span><b>72.4%</b><small className="up">↑ 4.2% 지난주 대비</small></div><div><span>평균 풀이 시간</span><b>01:18</b><small>총 12문제</small></div><div><span>학습 일수</span><b>8일</b><small>이번 달</small></div></div><div className="history-section"><div className="section-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>최근 풀이 내역</h2></div><button className="filter">전체 영역 ▾</button></div><div className="history-list">{[{a:"의사소통 국어", q:"핵심 내용을 찾아보세요", score:"정답", time:"오늘 오전 10:24", c:"coral", id:"korean"},{a:"수리활용 영역", q:"변화율을 계산해보세요", score:"정답", time:"어제 오후 4:12", c:"mint", id:"math"},{a:"문제해결 영역", q:"우선순위를 정해보세요", score:"오답", time:"7월 26일 오후 2:08", c:"purple", id:"problem"}].map((r) => <div className="history-item" key={r.q}><span className={`round-icon ${r.c}`}>{r.a[0]}</span><div><b>{r.q}</b><small>{r.a} · {r.time}</small></div><span className={r.score === "정답" ? "result good" : "result bad"}>{r.score}</span><button className="retry" onClick={() => onRetry(r.id)}>다시 풀기 →</button></div>)}</div></div></div> }

function WrongView({ onRetry }: { onRetry: (id: string) => void }) { return <div className="page"><div className="page-title"><p className="eyebrow">WRONG ANSWERS</p><h1>오답노트</h1><p>틀린 문제를 다시 풀고, 약점을 실력으로 바꿔보세요.</p></div><div className="wrong-banner"><span>♡</span><div><b>3개의 문제</b>를 복습하면<br />취약 개념 <strong>‘핵심 내용 요약’</strong>을 보완할 수 있어요.</div><button className="primary" onClick={() => onRetry("korean")}>복습 시작 →</button></div><div className="wrong-list"><div className="section-heading"><h2>저장한 문제</h2><span>3문제</span></div>{questions.map((q) => <div className="wrong-item" key={q.id}><div><span className="tag coral">{q.area === "math" ? "수리활용" : q.area === "english" ? "영어" : "국어"}</span><b>{q.title}</b><small>취약 개념 · {q.concept}</small></div><button className="secondary" onClick={() => onRetry(q.area)}>다시 풀기</button></div>)}</div></div> }
